<a href="https://colab.research.google.com/github/ips610/UML501-Machine-Learning-Course-TIET/blob/main/UML501_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 6, 4, 5])
print(f'Array: {arr}')
print(f'Reversed Array: {arr[::-1]}')
print(f'Reversed Array: {np.flip(arr)}')

Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]
Reversed Array: [5 4 6 3 2 1]


In [7]:
arr = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(f'Flattened Array: {arr.flatten()}')
print(f'Flattened Array: {arr.ravel()}')
print(f'Flattened Array: {arr.reshape(-1)}')

Flattened Array: [1 2 3 2 4 5 1 2 3]
Flattened Array: [1 2 3 2 4 5 1 2 3]
Flattened Array: [1 2 3 2 4 5 1 2 3]


In [11]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 5]])

print(f'{np.equal(arr1, arr2)}')
print(f'{arr1 == arr2}')
print(f'Output: {np.array_equal(arr1, arr2)}')

[[ True  True]
 [ True False]]
[[ True  True]
 [ True False]]
Output: False


In [12]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

# Find the most frequent value
most_frequent_value = np.bincount(x).argmax()
print(f"Most frequent value: {most_frequent_value}")

# Find the indices of the most frequent value
indices = np.where(x == most_frequent_value)[0]
print(f"Indices of the most frequent value: {indices}")



# Find the most frequent value
most_frequent_value = np.bincount(y).argmax()
print(f"Most frequent value: {most_frequent_value}")

# Find the indices of the most frequent value
indices = np.where(y == most_frequent_value)[0]
print(f"Indices of the most frequent value: {indices}")

Most frequent value: 1
Indices of the most frequent value: [0 5 7 8 9]
Most frequent value: 1
Indices of the most frequent value: [0 1 2]


In [14]:
def find_most_frequent_value_and_indices(array):
    # Find the unique values and their counts
    values, counts = np.unique(array, return_counts=True)

    # Find the most frequent value
    most_frequent_value = values[np.argmax(counts)]

    # Find the indices of the most frequent value
    indices = np.where(array == most_frequent_value)[0]

    return most_frequent_value, indices

print(find_most_frequent_value_and_indices(x))
print(find_most_frequent_value_and_indices(y))

(1, array([0, 5, 7, 8, 9]))
(1, array([0, 1, 2]))


In [15]:
array = np.array([1, 3, 2, 1, 4, 1, 3, 3, 3, 2, 1])

# Find the counts of all values
counts = np.bincount(array)
print(f"Counts: {counts}")

# Identify the maximum count
max_count = counts.max()
print(f"Maximum count: {max_count}")

# Find all values that have the maximum count
most_frequent_values = np.flatnonzero(counts == max_count)
print(f"Most frequent values: {most_frequent_values}")

# Find the indices of these most frequent values in the original array
indices_dict = {value: np.where(array == value)[0] for value in most_frequent_values}
print(f"Indices of the most frequent values: {indices_dict}")

Counts: [0 4 2 4 1]
Maximum count: 4
Most frequent values: [1 3]
Indices of the most frequent values: {1: array([ 0,  3,  5, 10]), 3: array([1, 6, 7, 8])}


In [66]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(f'Sum: {np.sum(gfg)}')
print(f'Row Wise Sum: {np.sum(gfg, axis=1)}')
print(f'Second Row Sum: {np.sum(gfg, axis=1)[1]}')
print(f'Column Wise Sum: {np.sum(gfg, axis=0)}')
xyz = np.sum(gfg, axis=0)
print(type(xyz))
print(xyz.shape)
xyz[0]

# Bottom Code work perfectly

# # Define the matrix correctly as a NumPy array
# gfg = np.array([[4, 1, 9], [12, 3, 1], [4, 5, 6]])

# # Sum of all elements
# print(f'Sum: {np.sum(gfg)}')

# # Sum of elements row-wise
# print(f'Row Wise Sum: {np.sum(gfg, axis=1)}')

# # Sum of the second row
# print(f'Second Row Sum: {np.sum(gfg, axis=1)[1]}')

# # Sum of elements column-wise
# print(f'Column Wise Sum: {np.sum(gfg, axis=0)}')

# # Store column-wise sums in xyz
# xyz = np.sum(gfg, axis=0)

# # Type and shape of xyz
# print(type(xyz))  # Should print <class 'numpy.ndarray'>
# print(xyz.shape)  # Should print (3,)

# # Correctly access the sum of the first column
# print(xyz[0])  # This is the sum of the first column


Sum: 45
Row Wise Sum: [[14]
 [16]
 [15]]
Second Row Sum: [[16]]
Column Wise Sum: [[20  9 16]]
<class 'numpy.matrix'>
(1, 3)


matrix([[20,  9, 16]])

In [29]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

# i. Sum of diagonal elements
sum_diagonal_elements = np.trace(n_array)
print(f"Sum of diagonal elements: {sum_diagonal_elements}")

# ii. Eigenvalues of the matrix
eigenvalues = np.linalg.eigvals(n_array)
print(f"Eigenvalues of the matrix: {eigenvalues}")

# iii. Eigenvectors of the matrix
eigenvalues, eigenvectors = np.linalg.eig(n_array)
print(f"Eigenvectors of the matrix: {eigenvectors}")

# iv. Inverse of the matrix
inverse_matrix = np.linalg.inv(n_array)
print(f"Inverse of the matrix: {inverse_matrix}")

# v. Determinant of the matrix
determinant = np.linalg.det(n_array)
print(f"Determinant of the matrix: {determinant}")

Sum of diagonal elements: 176
Eigenvalues of the matrix: [98.16835147 28.097044   49.73460452]
Eigenvectors of the matrix: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of the matrix: [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of the matrix: 137180.0000000001


In [72]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

print(f'Mutiplication: {p1*q1}')
print(f'Dot Product: {np.dot(p1, q1)}')
print(f'Multiplication: {np.matmul(p1, q1)}')
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

result2 = np.matmul(p2, q2)
print(f'Multiplication of p2 and q2:\n{result2}')

# Flatten matrices to 1D arrays
p1_flat = p1.flatten()
q1_flat = q1.flatten()

# Stack matrices vertically and calculate covariance matrix
cov_matrix = np.cov(p1_flat, q1_flat)
print(f'Covariance matrix between p1 and q1:\n{cov_matrix}')

# Flatten matrices to 1D arrays
p2_flat = p2.flatten()
q2_flat = q2.flatten()

# Stack matrices vertically and calculate covariance matrix
cov_matrix = np.cov(p2_flat, q2_flat)
print(f'Covariance matrix between p2 and q2:\n{cov_matrix}')

# Define matrices x and y
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Inner product (dot product)
inner_product = np.inner(x, y)
print(f'Inner product of x and y:\n{inner_product}')

# Define vectors (flatten x and y)
x_flat = x.flatten()
y_flat = y.flatten()

# Outer product
outer_product = np.outer(x_flat, y_flat)
print(f'Outer product of x and y:\n{outer_product}')

# Cartesian product using broadcasting
cartesian_product = np.einsum('ij,kl->ijkl', x, y)
print(f'Cartesian product of x and y:\n{cartesian_product}')


Mutiplication: [[ 4 10]
 [12 21]]
Dot Product: [[16 19]
 [26 31]]
Multiplication: [[16 19]
 [26 31]]
Multiplication of p2 and q2:
[[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance matrix between p1 and q1:
[[0.66666667 1.        ]
 [1.         1.66666667]]
Covariance matrix between p2 and q2:
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]
Inner product of x and y:
[[17 52]
 [13 62]]
Outer product of x and y:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product of x and y:
[[[[ 2 10  0]
   [10 20  6]]

  [[ 3 15  0]
   [15 30  9]]

  [[ 4 20  0]
   [20 40 12]]]


 [[[ 3 15  0]
   [15 30  9]]

  [[ 2 10  0]
   [10 20  6]]

  [[ 9 45  0]
   [45 90 27]]]]


In [73]:
array = np.array([[1, -2, 3], [-4, 5, -6]])

In [74]:
abs_array = np.abs(array)
print(f'Element-wise absolute value:\n{abs_array}')

Element-wise absolute value:
[[1 2 3]
 [4 5 6]]


In [75]:
percentiles_flat = np.percentile(array.flatten(), [25, 50, 75])
print(f'25th, 50th, and 75th percentiles of flattened array:\n{percentiles_flat}')


25th, 50th, and 75th percentiles of flattened array:
[-3.5 -0.5  2.5]


In [76]:
percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)
print(f'25th, 50th, and 75th percentiles for each column:\n{percentiles_columns}')


25th, 50th, and 75th percentiles for each column:
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]


In [77]:
percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)
print(f'25th, 50th, and 75th percentiles for each row:\n{percentiles_rows}')


25th, 50th, and 75th percentiles for each row:
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [80]:
mean_flat = np.mean(array.flatten())
median_flat = np.median(array.flatten())
std_flat = np.std(array.flatten())

print(f'Mean of flattened array: {mean_flat}')
print(f'Median of flattened array: {median_flat}')
print(f'Standard Deviation of flattened array: {std_flat}')


Mean of flattened array: -0.5
Median of flattened array: -0.5
Standard Deviation of flattened array: 3.8622100754188224


In [82]:
mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)

print(f'Mean of each column:\n{mean_columns}')
print(f'Median of each column:\n{median_columns}')
print(f'Standard Deviation of each column:\n{std_columns}')


mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

print(f'Mean of each row:\n{mean_rows}')
print(f'Median of each row:\n{median_rows}')
print(f'Standard Deviation of each row:\n{std_rows}')



Mean of each column:
[-1.5  1.5 -1.5]
Median of each column:
[-1.5  1.5 -1.5]
Standard Deviation of each column:
[2.5 3.5 4.5]
Mean of each row:
[ 0.66666667 -1.66666667]
Median of each row:
[ 1. -4.]
Standard Deviation of each row:
[2.05480467 4.78423336]


In [85]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_values = np.floor(a)
print(f'Floor values:\n{floor_values}')

ceiling_values = np.ceil(a)
print(f'Ceiling values:\n{ceiling_values}')

trunc_values = np.trunc(a)
print(f'Truncated values:\n{trunc_values}')

round_values = np.round(a)
print(f'Rounded values:\n{round_values}')

Floor values:
[-2. -2. -1.  0.  1.  1.  3.]
Ceiling values:
[-1. -1. -0.  1.  2.  2.  3.]
Truncated values:
[-1. -1. -0.  0.  1.  1.  3.]
Rounded values:
[-2. -2. -0.  0.  2.  2.  3.]


In [88]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array = np.sort(array)
print(f'Sorted array:\n{sorted_array}')

sorted_indices = np.argsort(array)
print(f'Indices of sorted array:\n{sorted_indices}')

four_smallest = np.partition(array, 4)[:4]
print(f'4 smallest elements:\n{four_smallest}')

four_smallest = np.sort(array)[:4]
print(f'4 smallest elements:\n{four_smallest}')

five_largest = np.partition(array, -5)[-5:]
print(f'5 largest elements:\n{five_largest}')

five_largest = np.sort(array)[-5:]
print(f'5 largest elements:\n{five_largest}')


Sorted array:
[ 10  16  16  52  54  62 453]
Indices of sorted array:
[0 3 4 1 5 2 6]
4 smallest elements:
[16 10 16 52]
4 smallest elements:
[10 16 16 52]
5 largest elements:
[ 16  52  62  54 453]
5 largest elements:
[ 16  52  54  62 453]


In [89]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

integer_elements = array[array.astype(int) == array]
print(f'Integer elements only:\n{integer_elements}')

unique_elements = np.unique(array)
print(f'Unique elements:\n{unique_elements}')

float_elements = array[array.astype(int) != array]
print(f'Float elements only:\n{float_elements}')


Integer elements only:
[1. 2. 3. 2.]
Unique elements:
[1.  1.2 2.  2.2 3. ]
Float elements only:
[1.2 2.2]
